// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260923155217_AddHotelAndReservationRelationships")]
    partial class AddHotelAndReservationRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "b9e6f7a9-09b0-4c7b-a4e3-cc892e5fb96b",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "c9e5e2b4-05c2-6c1a-b4e3-ec234e5db42c",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("api.Models.ApiUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("api.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tehran"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mashhad"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Isfahan"
                        });
                });

            modelBuilder.Entity("api.Models.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HotelId")
                        .HasColumnType("integer");

                    b.Property<string>("Meal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Drink");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Traditional black tea served hot.",
                            HotelId = 1,
                            Meal = "Breakfast",
                            Name = "Persian Tea",
                            Price = 3m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Freshly squeezed orange juice.",
                            HotelId = 1,
                            Meal = "Breakfast",
                            Name = "Fresh Orange Juice",
                            Price = 5m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fresh pomegranate juice.",
                            HotelId = 1,
                            Meal = "Lunch",
                            Name = "Pomegranate Juice",
                            Price = 6m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Traditional chilled yogurt drink with dried mint.",
                            HotelId = 1,
                            Meal = "Lunch",
                            Name = "Doogh",
                            Price = 4m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Chilled Persian saffron and rose water drink.",
                            HotelId = 1,
                            Meal = "Dinner",
                            Name = "Saffron Sherbet",
                            Price = 5m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Fresh lemon juice, mint and sparkling water.",
                            HotelId = 1,
                            Meal = "Dinner",
                            Name = "Mint Lemonade",
                            Price = 5m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Freshly brewed single espresso.",
                            HotelId = 1,
                            Meal = "Breakfast",
                            Name = "Espresso",
                            Price = 4m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Espresso with hot water.",
                            HotelId = 1,
                            Meal = "Breakfast",
                            Name = "Americano",
                            Price = 5m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Black tea infused with saffron.",
                            HotelId = 2,
                            Meal = "Breakfast",
                            Name = "Saffron Tea",
                            Price = 4m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Freshly prepared pomegranate juice.",
                            HotelId = 2,
                            Meal = "Lunch",
                            Name = "Pomegranate Juice",
                            Price = 6m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Cold traditional yogurt drink with mint.",
                            HotelId = 2,
                            Meal = "Lunch",
                            Name = "Doogh",
                            Price = 4m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Refreshing juice made from Iranian barberries.",
                            HotelId = 2,
                            Meal = "Lunch",
                            Name = "Barberry Juice",
                            Price = 5m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Chilled rose water drink with a delicate floral flavor.",
                            HotelId = 2,
                            Meal = "Dinner",
                            Name = "Rose Water Sherbet",
                            Price = 5m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Fresh lemon, mint and sparkling water served chilled.",
                            HotelId = 2,
                            Meal = "Dinner",
                            Name = "Lemon Mint Cooler",
                            Price = 5m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Strong traditionally brewed coffee.",
                            HotelId = 2,
                            Meal = "Breakfast",
                            Name = "Turkish Coffee",
                            Price = 4m
                        },
                        new
                        {
                            Id = 18,
                            Description = "Espresso with steamed milk and foam.",
                            HotelId = 2,
                            Meal = "Breakfast",
                            Name = "Cappuccino",
                            Price = 6m
                        },
                        new
                        {
                            Id = 21,
                            Description = "Traditional Iranian black tea served hot.",
                            HotelId = 3,
                            Meal = "Breakfast",
                            Name = "Persian Black Tea",
                            Price = 3m
                        },
                        new
                        {
                            Id = 22,
                            Description = "Refreshing traditional sour cherry juice.",
                            HotelId = 3,
                            Meal = "Lunch",
                            Name = "Sour Cherry Juice",
                            Price = 5m
                        },
                        new
                        {
                            Id = 23,
                            Description = "Chilled yogurt drink with mint and a lightly salted flavor.",
                            HotelId = 3,
                            Meal = "Lunch",
                            Name = "Doogh",
                            Price = 4m
                        },
                        new
                        {
                            Id = 24,
                            Description = "Fresh pomegranate juice served chilled.",
                            HotelId = 3,
                            Meal = "Lunch",
                            Name = "Pomegranate Juice",
                            Price = 6m
                        },
                        new
                        {
                            Id = 25,
                            Description = "Traditional chilled rose water drink.",
                            HotelId = 3,
                            Meal = "Dinner",
                            Name = "Rose Water Sherbet",
                            Price = 5m
                        },
                        new
                        {
                            Id = 26,
                            Description = "Fresh lemon drink infused with saffron.",
                            HotelId = 3,
                            Meal = "Dinner",
                            Name = "Saffron Lemonade",
                            Price = 5m
                        },
                        new
                        {
                            Id = 27,
                            Description = "Black tea brewed with cardamom and saffron.",
                            HotelId = 3,
                            Meal = "Breakfast",
                            Name = "Persian Cardamom Tea",
                            Price = 4m
                        },
                        new
                        {
                            Id = 28,
                            Description = "Strong traditionally brewed coffee served in a small cup.",
                            HotelId = 3,
                            Meal = "Breakfast",
                            Name = "Turkish Coffee",
                            Price = 4m
                        });
                });

            modelBuilder.Entity("api.Models.Factor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiUserId")
                        .IsUnique();

                    b.HasIndex("ReservationId");

                    b.ToTable("Factor");
                });

            modelBuilder.Entity("api.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HotelId")
                        .HasColumnType("integer");

                    b.Property<string>("Meal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Food");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Two grilled koobideh kebabs served with saffron rice, grilled tomato and butter.",
                            HotelId = 1,
                            Meal = "Lunch",
                            Name = "Chelo Kebab Koobideh",
                            Price = 18m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Grilled marinated beef fillet served with saffron rice and grilled tomato.",
                            HotelId = 1,
                            Meal = "Lunch",
                            Name = "Chelo Kebab Barg",
                            Price = 24m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Persian herb stew with kidney beans, dried lime and tender beef, served with rice.",
                            HotelId = 1,
                            Meal = "Lunch",
                            Name = "Ghormeh Sabzi",
                            Price = 16m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Chicken cooked in a rich walnut and pomegranate sauce, served with saffron rice.",
                            HotelId = 1,
                            Meal = "Dinner",
                            Name = "Fesenjan",
                            Price = 19m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Saffron rice with barberries and roasted chicken.",
                            HotelId = 1,
                            Meal = "Dinner",
                            Name = "Zereshk Polo Ba Morgh",
                            Price = 17m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Saffron-marinated grilled chicken pieces served with rice and grilled vegetables.",
                            HotelId = 1,
                            Meal = "Dinner",
                            Name = "Joojeh Kebab",
                            Price = 17m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Persian yogurt with cucumber, dried mint and herbs.",
                            HotelId = 1,
                            Meal = "Starter",
                            Name = "Mast-o-Khiar",
                            Price = 7m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Roasted eggplant dip topped with whey, fried onions, walnuts and mint.",
                            HotelId = 1,
                            Meal = "Starter",
                            Name = "Kashk-e Bademjan",
                            Price = 9m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Fresh bread, feta cheese, walnuts, cucumber, tomato, butter and honey.",
                            HotelId = 1,
                            Meal = "Breakfast",
                            Name = "Persian Breakfast",
                            Price = 11m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Traditional Persian ice cream flavored with saffron, rose water and pistachios.",
                            HotelId = 1,
                            Meal = "Dessert",
                            Name = "Saffron Ice Cream",
                            Price = 8m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Tender grilled lamb chops marinated with saffron and served with rice.",
                            HotelId = 2,
                            Meal = "Lunch",
                            Name = "Shishlik",
                            Price = 27m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Grilled kebab served with saffron rice, grilled tomato and fresh herbs.",
                            HotelId = 2,
                            Meal = "Lunch",
                            Name = "Chelo Kebab Mashhadi",
                            Price = 19m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Split pea stew with beef, tomato and dried lime served with rice.",
                            HotelId = 2,
                            Meal = "Lunch",
                            Name = "Mashhadi Gheymeh",
                            Price = 15m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Persian rice with noodles, raisins and dates served with tender chicken.",
                            HotelId = 2,
                            Meal = "Lunch",
                            Name = "Reshteh Polo",
                            Price = 16m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Saffron rice with fava beans and dill served with slow-cooked lamb shank.",
                            HotelId = 2,
                            Meal = "Dinner",
                            Name = "Baghali Polo Ba Mahicheh",
                            Price = 25m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Combination of koobideh and barg kebab served with saffron rice.",
                            HotelId = 2,
                            Meal = "Dinner",
                            Name = "Kebab Soltani",
                            Price = 26m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Traditional thick soup with beans, herbs, noodles and whey.",
                            HotelId = 2,
                            Meal = "Starter",
                            Name = "Ash Reshteh",
                            Price = 10m
                        },
                        new
                        {
                            Id = 18,
                            Description = "Smoked eggplant with tomato, garlic and egg.",
                            HotelId = 2,
                            Meal = "Starter",
                            Name = "Mirza Ghasemi",
                            Price = 9m
                        },
                        new
                        {
                            Id = 19,
                            Description = "Eggs, cheese, butter, honey, jam, fresh bread, cucumber and tomato.",
                            HotelId = 2,
                            Meal = "Breakfast",
                            Name = "Hotel Breakfast",
                            Price = 12m
                        },
                        new
                        {
                            Id = 20,
                            Description = "Traditional Persian saffron rice pudding with cinnamon and pistachios.",
                            HotelId = 2,
                            Meal = "Dessert",
                            Name = "Sholeh Zard",
                            Price = 7m
                        },
                        new
                        {
                            Id = 21,
                            Description = "Traditional Isfahani minced lamb and herbs served with freshly baked bread.",
                            HotelId = 3,
                            Meal = "Lunch",
                            Name = "Beryani",
                            Price = 18m
                        },
                        new
                        {
                            Id = 22,
                            Description = "Sweet and creamy Isfahani yogurt dessert made with saffron and orange zest.",
                            HotelId = 3,
                            Meal = "Dessert",
                            Name = "Khoresht Mast",
                            Price = 9m
                        },
                        new
                        {
                            Id = 23,
                            Description = "Chicken in walnut and pomegranate sauce served with saffron rice.",
                            HotelId = 3,
                            Meal = "Lunch",
                            Name = "Khoresht Fesenjan",
                            Price = 19m
                        },
                        new
                        {
                            Id = 24,
                            Description = "Tender beef and yellow plum stew served with Persian saffron rice.",
                            HotelId = 3,
                            Meal = "Lunch",
                            Name = "Khoresht Alu",
                            Price = 17m
                        },
                        new
                        {
                            Id = 25,
                            Description = "Smoked eggplant topped with whey, walnuts, mint and fried onions.",
                            HotelId = 3,
                            Meal = "Starter",
                            Name = "Kashk-e Bademjan",
                            Price = 9m
                        },
                        new
                        {
                            Id = 26,
                            Description = "Grape leaves stuffed with rice, herbs and seasoned meat.",
                            HotelId = 3,
                            Meal = "Starter",
                            Name = "Dolmeh Barg",
                            Price = 12m
                        },
                        new
                        {
                            Id = 27,
                            Description = "Persian rice with lentils, raisins and dates served with roasted chicken.",
                            HotelId = 3,
                            Meal = "Dinner",
                            Name = "Adas Polo",
                            Price = 16m
                        },
                        new
                        {
                            Id = 28,
                            Description = "Saffron-marinated chicken kebab served with rice and grilled vegetables.",
                            HotelId = 3,
                            Meal = "Dinner",
                            Name = "Joojeh Kebab",
                            Price = 17m
                        },
                        new
                        {
                            Id = 29,
                            Description = "Fresh bread, local cheese, walnuts, honey, cream, cucumber and tomato.",
                            HotelId = 3,
                            Meal = "Breakfast",
                            Name = "Traditional Isfahani Breakfast",
                            Price = 11m
                        },
                        new
                        {
                            Id = 30,
                            Description = "Traditional Isfahani nougat made with pistachios and rose water.",
                            HotelId = 3,
                            Meal = "Dessert",
                            Name = "Gaz",
                            Price = 8m
                        });
                });

            modelBuilder.Entity("api.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Hotel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Valiasr Street, Tehran",
                            CityId = 1,
                            Description = "A luxury hotel in central Tehran.",
                            Name = "Grand Tehran Hotel",
                            Phone = "02112345678"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Imam Reza Street, Mashhad",
                            CityId = 2,
                            Description = "A comfortable hotel near the holy shrine.",
                            Name = "Mashhad Palace Hotel",
                            Phone = "05112345678"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Naqsh-e Jahan Square, Isfahan",
                            CityId = 3,
                            Description = "A traditional hotel in historic Isfahan.",
                            Name = "Isfahan Heritage Hotel",
                            Phone = "03112345678"
                        });
                });

            modelBuilder.Entity("api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("boolean");

                    b.Property<int>("ReservationId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ApiUserId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("api.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DrinkId")
                        .HasColumnType("integer");

                    b.Property<int?>("FoodId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("DrinkId");

                    b.HasIndex("FoodId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("api.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CheckinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HotelId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiUserId");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("api.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePricePerDay")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("BedNumbers")
                        .HasColumnType("integer");

                    b.Property<int>("HotelId")
                        .HasColumnType("integer");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePricePerDay = 50m,
                            BedNumbers = 1,
                            HotelId = 1,
                            RoomNumber = "101"
                        },
                        new
                        {
                            Id = 2,
                            BasePricePerDay = 80m,
                            BedNumbers = 2,
                            HotelId = 1,
                            RoomNumber = "102"
                        },
                        new
                        {
                            Id = 3,
                            BasePricePerDay = 70m,
                            BedNumbers = 2,
                            HotelId = 2,
                            RoomNumber = "201"
                        },
                        new
                        {
                            Id = 4,
                            BasePricePerDay = 100m,
                            BedNumbers = 3,
                            HotelId = 2,
                            RoomNumber = "202"
                        },
                        new
                        {
                            Id = 5,
                            BasePricePerDay = 75m,
                            BedNumbers = 2,
                            HotelId = 3,
                            RoomNumber = "301"
                        });
                });

            modelBuilder.Entity("api.Models.RoomService", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("RoomId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("RoomService");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            RoomId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            RoomId = 2,
                            ServiceId = 1
                        },
                        new
                        {
                            RoomId = 2,
                            ServiceId = 3
                        },
                        new
                        {
                            RoomId = 3,
                            ServiceId = 1
                        },
                        new
                        {
                            RoomId = 4,
                            ServiceId = 1
                        },
                        new
                        {
                            RoomId = 4,
                            ServiceId = 2
                        },
                        new
                        {
                            RoomId = 5,
                            ServiceId = 1
                        });
                });

            modelBuilder.Entity("api.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Service");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Daily room cleaning.",
                            Name = "Room Cleaning",
                            Price = 10m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Breakfast delivered to the room.",
                            Name = "Breakfast Service",
                            Price = 15m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Laundry and ironing service.",
                            Name = "Laundry",
                            Price = 12m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("api.Models.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("api.Models.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("api.Models.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.Drink", b =>
                {
                    b.HasOne("api.Models.Hotel", "Hotel")
                        .WithMany("Drinks")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("api.Models.Factor", b =>
                {
                    b.HasOne("api.Models.ApiUser", "User")
                        .WithOne("Factor")
                        .HasForeignKey("api.Models.Factor", "ApiUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId");

                    b.Navigation("Reservation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.Food", b =>
                {
                    b.HasOne("api.Models.Hotel", "Hotel")
                        .WithMany("Foods")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("api.Models.Hotel", b =>
                {
                    b.HasOne("api.Models.City", "City")
                        .WithMany("Hotels")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("api.Models.Order", b =>
                {
                    b.HasOne("api.Models.ApiUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("ApiUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.OrderItem", b =>
                {
                    b.HasOne("api.Models.Drink", "Drink")
                        .WithMany()
                        .HasForeignKey("DrinkId");

                    b.HasOne("api.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId");

                    b.HasOne("api.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");

                    b.Navigation("Food");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("api.Models.Reservation", b =>
                {
                    b.HasOne("api.Models.ApiUser", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("ApiUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Hotel", null)
                        .WithMany("Reservations")
                        .HasForeignKey("HotelId");

                    b.HasOne("api.Models.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.Room", b =>
                {
                    b.HasOne("api.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("api.Models.RoomService", b =>
                {
                    b.HasOne("api.Models.Room", "Room")
                        .WithMany("RoomServices")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Service", "Service")
                        .WithMany("RoomServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("api.Models.ApiUser", b =>
                {
                    b.Navigation("Factor")
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("api.Models.City", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("api.Models.Hotel", b =>
                {
                    b.Navigation("Drinks");

                    b.Navigation("Foods");

                    b.Navigation("Reservations");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("api.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("api.Models.Room", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("RoomServices");
                });

            modelBuilder.Entity("api.Models.Service", b =>
                {
                    b.Navigation("RoomServices");
                });
#pragma warning restore 612, 618
        }
    }
}
